### ISSUE TITLE
Incorrect enemy placed?

### ISSUE THREAD

**Issue by DoctorGoat** [XKirby/MMBN3-Randomizer#1]
`Seed: Sat Oct 10 09:56:48 2020
Hash: 24 4 d-3a 1c 65-71 37 1a-35 a 12-9 d 53
Chip Damage Multiplier: 1.0
Chip Damage Variance: 0.5
Enemy HP Multiplier: 1.0
Enemy HP Variance: 0.5
Chip Codes Mode: 2
Randomized Chip Names?: False
Randomized Enemy Names?: False
Randomized NaviCust Shapes?: True
Random Battlefield Mode: 0
Random Element Mode: 0
Randomize Navis?: True
Folder Lock Mode: 0
OMEGA Mode: 0
RegMem Max Range: 0
HELL Mode: 0`

Battle #264: ShrimpyO (32) -> MegaMan (0)
Battle #1123: EleballO (142) -> MegaMan (0)
A number of these battles are showing up as against Megaman. It's mostly involving Omega viruses, however.

**Comment by XKirby** [comment]
I might know why this happens, but I'm unsure if this actually sets their value to 0 or not. It could just be a display error in the output log. If it does set their value to 0, I'll have to figure out why. Which version of the Randomizer are you running?

**Comment by DoctorGoat** [comment]
I've never run into one, and they mostly seem to be replacing Omega enemies. It would've been the current version as of Oct 10;

**Comment by XKirby** [comment]
I'll look into this. Thanks for the head's up.

**Comment by XKirby** [comment]
Fixed as of v3.5.4.
