### ISSUE TITLE
Zenny drops from battle being randomized with chip data

### ISSUE THREAD

**Issue by Drakonas** [XKirby/MMBN3-Randomizer#10]
Is it intended for zenny drops from battle being randomized with chip data? It becomes very difficult to get money when all the zenny drops just give me chips every time. My folder is loaded with HeatSide and Rope chips regardless of what viruses I fight.

**Comment by XKirby** [comment]
This was intentionally left in from a very old version of the randomizer to make chips easier to farm for. As a result of this, zenny drops from Mystery Datas are multiplied by 1.5x.

**Comment by Drakonas** [comment]
Understood. It's just very irritating.

**Comment by XKirby** [comment]
Honestly speaking, I could probably change this behavior and make it a toggle. Better to do that than to leave you frustrated. I'll see what I can do.

**Comment by XKirby** [comment]
@Drakonas Please check out version 5.1. I've added two settings to potentially help with your frustrations. While I didn't add a multiplier to Zenny dropped by battle, it's probably fine as-is for now. Hopefully the new options help you enjoy the game more.
