### ISSUE TITLE
Stuck at Randomizing 

### ISSUE THREAD

**Issue by Crystyanyan** [XKirby/MMBN3-Randomizer#11]
I really really want to try this randomizer but i've been having issues with it. After inputting all data in the executable it just stays on "randomizing". I can click again the randomize button and after 3 seconds where the window isn't responding it does the same thing. There is nothing being created in the folder even after up to 15 minutes. Any help? I tried asking on other places as well but in the end who better to ask than the creator. 

Hope you can see this message

**Comment by XKirby** [comment]
I talked with this person over Discord, turns out there was a bug with how Elements were being set with the Element Mode options, specifically with Battle Chips/PAs. This has been addressed with the latest release.
