### ISSUE TITLE
Potential Softlock

### ISSUE THREAD

**Issue by Conquest64** [XKirby/MMBN3-Randomizer#13]
Hi there,

Recently tried to start a randomized run of the game. Everything was going smoothly until start of the Bubbleman chapter. I am required to provide Higsby a Wind * (which has been randomized to a Poison Mask A). I have farmed the viruses in yoka 1 where you would normally get Wind * but have not found any encounters that drop Poison Mask A. Currently can't progress unless I can locate this rogue chip. On another seed the randomized chip became a Recovery 30 M and that chip has been equally elusive. Is there a setting or fix to progress?
[Megaman - Battle Network 3 - White Version (USA)_randomized.gba.mmbn3.w.log(jWK Vun suC zwa 6Fv).txt](https://github.com/XKirby/MMBN3-Randomizer/files/10421693/Megaman.-.Battle.Network.3.-.White.Version.USA._randomized.gba.mmbn3.w.log.jWK.Vun.suC.zwa.6Fv.txt)

**Comment by XKirby** [comment]
Check the Chips in CyberACDC Area 2. The Story-related chips should be sold there for 100 Zenny, if you enabled randomized shops.

**Comment by XKirby** [comment]
I'm guessing you're good since there's no response. Apologies I responded so late.
