### ISSUE TITLE
Possible softlock

### ISSUE THREAD

**Issue by DoctorGoat** [XKirby/MMBN3-Randomizer#2]
Same seed and settings as the other issue.

I do not seem to have a FlamMan that will open the cube. FlamMan Beta replaces Bubbleman Beta in Yoka 1, and slaughtering him in fifteen seconds wasn't enough to make the cube in the Undernet open.

Nobody has randomized into FlamMan whatsoever. I was thinking it'd be YamatoMan, but YamatoMan is Protoman.

[battles.txt](https://github.com/XKirby/MMBN3-Randomizer/files/5458748/battles.txt)

**Comment by XKirby** [comment]
The encounter location with FlamMan Beta is supposed to unlock the cube, but if it isn't then there's definitely a bug. Which version of the Randomizer are you using?

**Comment by DoctorGoat** [comment]
Huhn. I've killed the Yoka 1 encounter (BubbleMan, who I loathe fighting) a bunch of times. It should be 3.5.3.

**Comment by XKirby** [comment]
There are actually 2 V3 encounters in Yoka 1, and ironically, both of them are BubbleMan and FlamMan. You might be at the wrong encounter, but I'm not 100% sure. If your health is below 50%, BubbleMan shows up near the BugFrag Trader. If you're near the Water Heater, that's where FlamMan shows up and it's recommended, if not required, to use the OilBody NaviCust Program.

Which location are you at in Yoka 1?

**Comment by XKirby** [comment]
Turns out you're right and I was wrong about it being map event-related, you are soft-locked out of that area. Whoops. This will be fixed and uploaded shortly.

**Comment by XKirby** [comment]
Fixed as of v3.5.4.
