### ISSUE TITLE
Stuck on Job 9 "Will you deliver?"

### ISSUE THREAD

**Issue by Hexadigital** [XKirby/MMBN3-Randomizer#3]
Hello! Thank you for creating the randomizer, but I think I've run into an issue. I accepted Job 9, "Will you deliver?", in which you take a chip from an elderly lady in Yoka and bring it to a businessman in the TV Station.

The problem is: he doesn't seem to want to accept the chip. The chip I received, NoBeam2 D, is the same one that the lady references in her dialogue - but the businessman only says "That's too bad! Where's the chip!?". I'm not sure what chip he is looking for since he doesn't mention it.

If it is useful, here is my seed info:
Seed: Sun Nov 15 10:28:08 2020
Hash: 67 5a 1c-26 3f 11-4f 38 69-50 36 42-1d 63 5

(I can provide the rest of the options if needed, not sure how much is useful)

**Comment by Hexadigital** [comment]
Sorry, forgot to mention: this causes the player to be stuck in the storyline since you need to accept Tora's jobs during the Hospital arc.

**Comment by XKirby** [comment]
That's a new one, which is surprising. Please upload your entire output log so I can see what happened. Also, which version of the Randomizer are you using?

What probably happened was that the trade in question wasn't correctly randomized and I'll have to fix it.

**Comment by Hexadigital** [comment]
I'm using v3.6, grabbed it from ngplus.net if that makes a difference.

[mmbn3w_seedinfo - 67 5a 1c-26 3f 11-4f 38 69-50 36 42-1d 63 5.txt](https://github.com/XKirby/MMBN3-Randomizer/files/5593115/mmbn3w_seedinfo.-.67.5a.1c-26.3f.11-4f.38.69-50.36.42-1d.63.5.txt)

**Comment by XKirby** [comment]
Looking at your output log, it wasn't that the Trade wasn't randomized; the requirement became the wrong chip! Weird, but that can happen because of how the chip IDs are read by the randomizer. I'll have to see if I can fix this.

**Comment by Hexadigital** [comment]
In the meantime, do you know what chip it got set to? If it's a chip that I can find elsewhere, I'd like to go find it so I can continue playing :D

**Comment by XKirby** [comment]
Lance D

**Comment by Hexadigital** [comment]
Likewise, the second half of the job is also bugged - I got a SandStage D, but the navi expects a PoisFace F.
(Trade #16 Requirement)

**Comment by XKirby** [comment]
Thanks for the report! I posted an update yesterday to hopefully fix these problems. Please let me know if this helps.

**Comment by Hexadigital** [comment]
Thank you! I should have kept a copy of my save data before I farmed for Lance D and progressed, but I'll let you know if I run into any issues with future jobs.

Can I run the randomizer again with the same seed to get an "updated" copy of the game, or would that cause issues due to the changes with the Chaos Code Roulette Mode?

**Comment by XKirby** [comment]
If you weren't using the Chaos Mode for Chip Code Roulette, you should be fine to just re-randomize. I would highly recommend starting over anyway because the NPC Trades will have different results than what they were originally. Also, like before, make sure you export the detailed output log just in case.

Hopefully I managed to cover all of the story-required Trades that had the chips given to you by the game. I'll leave this open so that others can report their findings should something pop up.

EDIT: Seems like you were in fact using Chaos Mode. Sorry, but you're pretty much required to start over, things were heavily adjusted in regards to that option.

**Comment by XKirby** [comment]
I closed this issue as it hasn't been updated in a while with feedback. Please let me know if this happens again.
