### ISSUE TITLE
Trouble with randomizing. 

### ISSUE THREAD

**Issue by ReddJokahhX** [XKirby/MMBN3-Randomizer#5]
Hi, this is likely a very dumb question, but I have the correct rom type and I am giving the randomizer the correct path, but it keeps saying there's a permission error. What exactly am I doing wrong? 

It says: 

IOError: [Errno 13] Permission Denied. 

Sorry if this is an inconvenience to answer. Sadly I can't find a solution to this anywhere.

**Comment by MiUGlitchNoob** [comment]
Got the same problem :/

**Comment by MiUGlitchNoob** [comment]
Hey, you have to include your file name at the end of Input, example: C:\XXXXX\XXXXXX\Desktop\MMBN3 Randomizer\Megaman Battle Network 3 Blue (USA).gba

**Comment by ReddJokahhX** [comment]
Did that. Now I get this instead

"Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1547, in __call__
  File "bn3ui_support.py", line 147, in buttonRandomize
  File "bn3random.py", line 2154, in randomizerom
IOError: [Errno 13] Permission denied: 'mmbn3b_log (56-67-53 4f-34-8 10-66-18 72-a-2 58-12-1).txt'"

**Comment by XKirby** [comment]
Where are you attempting to run the randomizer from? Have you extracted it from the zip file?

EDIT: About to push an update anyway to address some other issues with the previous build, so please try with this new version in a second.

**Comment by ReddJokahhX** [comment]
Got it working! All good now, thanks a ton for the help guys.
