### ISSUE TITLE
Windows defender detecting trojan virus within the release zip

### ISSUE THREAD

**Issue by dombarrieau** [XKirby/MMBN3-Randomizer#7]
Windows Defender is detecting Win32/Wacatac.B!ml in the release 4.3.2 zip and identified it as a trojan.

**Comment by dombarrieau** [comment]
Spoke with the developer, look like it's a false positive caused by pyinstaller.

**Comment by XKirby** [comment]
I'm going to post here again to note that it was affecting "MMBN3 Randomizer Command Line.exe" specifically, and not the GUI one.

I've uploaded a build that _SHOULD_ be clean (v4.3.2.1). If it isn't, let me know, because I compiled and scanned it myself and nothing came up.
