### ISSUE TITLE
Blue Mystery data says it gives the correct chip data for a quest, but the given chip is wrong

### ISSUE THREAD

**Issue by Drakonas** [XKirby/MMBN3-Randomizer#9]
I picked up a Blue Mystery data that, as far as I can tell, was supposed to give the correct data. It said "you got a Rook Q", but what I actually got (I looked right away) was a Recov30 *

I thought nothing of it. Later I picked up the first quest in SciLab that requires a trade for a RegMem3. The quest details on the board says "Looking for a Recov30 *", so I figured that it properly changed the chip. But when I go to trade with the guy, he says "Oh you're the guy that took my request! I'm looking for a Rook Q."

So the trade becomes impossible, as he says I don't have the chip. Is it possible some of the address values weren't changed properly?

I did make sure the Recov30 * was not in my folder for the trade.

Another Blue mystery data later did the same thing. It said "You got this" but gave me a completely different chip.

```
Seed: Drakonas
Hash: s0a Q5N 7li Yxk pmz

Chip Damage Multiplier: 1.0
Chip Damage Variance: 0.0
Chip Price Variance: 0.0
Enemy HP Multiplier: 1.0
Enemy HP Variance: 0.0
Chip Codes Mode: 0
Randomized Chip Names?: False
Randomized Enemy Names?: False
Randomized NaviCust Shapes?: False
Random Battlefield Mode: 0
Random Element Mode: 0
Randomize Navis?: True
Folder Lock Mode: 5
OMEGA Mode: 0
RegMem Max Range: 0
HELL Mode: 0

Allow Folders?: True
Allow Blue Mystery Data?: True
Allow Green Mystery Data?: True
Allow Shops?: True
Allow Battle Chips?: True
Allow Viruses?: True
Allow NPC Trades?: True

Allow Easy Tutorial?: True
Randomize Battle Objects?: False
Free BattleChips in Shops?: False
Fill Shops?: True
Ignore HP/Damage Limiters?: False
```

**Comment by XKirby** [comment]
I'm going to double-check this, since it _was_ supposed to give you the correct chip. I'll get back to you once I see what happens.

**Comment by XKirby** [comment]
Which version of BN3 are you playing? I just tested on BN3 Blue and it worked as intended. Please also list the version of the Randomizer you're using.

**Comment by XKirby** [comment]
Confirmed working on both versions of BN3. Get back to me with your version of the randomizer and please check to see if your game matches the checksums listed on the main page.

**Comment by Drakonas** [comment]
The version I used was [5.0.1](https://github.com/XKirby/MMBN3-Randomizer/releases/tag/v5.0.1).

I was playing with White version. My checksum is CRC32: 0BE4410A. I used 7-zip to check the hash.

What I found was there was another blue mystery data later where it also said "You got a Rook Q", but this time I got the actual chip.

The earlier case said I got a Rook Q in the dialog, but when I looked at my chips it actually gave me a Recov30 *.

I find it odd that the quest instructions says he needs a Recov30 *, but when I talk to the quest giver, he states he needs a Rook Q. Not sure if something weird is going on, but considering the blue mystery data AND the quest dialog both flipped the two chips, I think something wrong is going on.

**Comment by Drakonas** [comment]
@XKirby After further testing, it does indeed seem to be running as normal... mostly. I think it was just unclear to me that the initial dialog will ask for one chip but then change that to the other. I'm not sure if this is due to dialogue changing limitations for parts of the game, which I understand. I was just confused when I picked up a blue mystery data, and it said I got a Rook Q, but instead I got a Recov30 *, the opposite of what was being asked (he asked for Recov30 * in the initial dialogue, but ended up wanting Rook Q.) A DIFFERENT blue mystery data said "You got Rook Q" and actually gave me the Rook Q I needed.

I'm not sure if this is just happenstance or an actual bug. If it is normal, then feel free to close the ticket. If the blue mystery data should be always giving me what it says it does, maybe investigating is necessary?

**Comment by XKirby** [comment]
@Drakonas It's normal behavior, though it is confusing visually (even to me at this point). Unfortunately, it'd take more effort to fix than I'd be willing to bother with due to how I'm searching through the Blue/Purple Mystery Datas.

Long story short, I'm only looking specifically for Trade results that match the BMDs. Because the Job BBS doesn't actually have the Trade textbox event ID with the matching battle chip/code, it's skipped.

Glad to know you're good to go though! Sorry this has baffled you for so long, I should have actually specified what was going on all that time ago.
